### ISSUE TITLE
`snap login` requires sudo

### ISSUE THREAD

**Issue by warsaw** [ubuntudesign/snapcraft.io#190]
In the tour, under section 30-STORE, we're told to login for both snapcraft and snap.  However, the `snap login` command seems to require sudo:

```
% snap login me@example.com
Password: 
error: access denied (try with sudo)
```

`sudo snap login` does seem to work though.

**Comment by nottrobin** [comment]
Thanks @warsaw

This looks like a bug with the application rather than with <http://snapcraft.io> the website. I'm afraid this issues list is only for bugs with the website itself. Although I agree it's confusing.

I've created [an issue to update the website](#191) with instructions for where to file bugs, and [a pull request](https://github.com/snapcore/snapd/pull/1780) back to the `snapd` project to mention the same.

Could you please re-file this issue [over on Launchpad](https://bugs.launchpad.net/snappy/+filebug)? I'm closing this now.

**Comment by nottrobin** [comment]
Sorry I was on an old version of `snapd`. I've updated and now I see this was valid. Sorry about that.
